0.8.9
nemtech/symbol-openapi-generator pull request #37
Opened 2020-03-23 16:55 UTC by fboucquez

2020-03-23 18:39 UTC, rg911 requested changes

2020-03-23 18:39 UTC, rg911 commented on patch-yml.sh
> +
empty lines

2020-03-24 02:15 UTC, fboucquez commented
Hi @rg911 , now Travis automatically downloads and patches open API spec from the github [releases](https://github.com/nemtech/symbol-openapi/releases).

So in the future, once David releases a new version of the spec, we need to just run the Travis build in master. No code change or PR is necessary :). If you run release build from Travis, it will just fire a new version, tagging, merging, etc.

https://travis-ci.org/github/nemtech/symbol-openapi-generator/branches?utm_medium=notification&utm_source=github_status

Fixes https://github.com/nemtech/symbol-openapi-generator/issues/21

2020-03-25 11:40 UTC, rg911 approved these changes

2020-03-25 12:36 UTC, merged